config/routes.rb
Rails.application.routes.draw do

  resources :genres

  get '/signin' => "sessions#new"
  resource :session

  get '/signup' => "users#new"
  resources :users

  get "/movies/filter/:scope" => "movies#index", as: :filtered_movies

  root "movies#index"
  resources :movies do
    resources :reviews
    resources :favorites
  end

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2013
    <%= link_to 'The Pragmatic Studio', 'http://pragmaticstudio.com' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div>
    <h1>Super Hero Flix!</h1>
    <nav>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <div>
        <% unless current_user %>
          <%= link_to "Sign In", signin_path %><br />
          <%= link_to 'Sign Up', signup_path %>
        <% else %>
          <%= link_to current_user.name, current_user %><br />
          <%= link_to "Account Settings", edit_user_path(current_user) %><br />
          <%= link_to 'Sign Out', session_path, method: :delete %>
        <% end %>
      </div>
      <br />
      <% if current_user_admin? %>
        <li><%= link_to "Add New Movie", new_movie_path  %></li>
      <% end %>
        <li><%= link_to "Released", movies_path %></li>
        <li><%= link_to "Hits", filtered_movies_path(:hits) %></li>
        <li><%= link_to "Flops", filtered_movies_path(:flops) %></li>
        <li><%= link_to "Upcoming", filtered_movies_path(:upcoming) %></li>
        <li><%= link_to "Recent", filtered_movies_path(:recent) %></li>
    </ul>
  </nav>
  <%= content_for :side %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <%= render 'layouts/flashes' %>
  <%= render 'layouts/sidebar' %>

  <%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>